In [2]:
from google.colab import drive
drive.mount ('/content/drive')
print ('Drive mounted!')

Mounted at /content/drive
Drive mounted!

In [3]:
import sys
print(f'Python Version is {sys.version}')

Python Version is 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

In [4]:
import pandas as pd
print(f'Pandas Version is {pd.__version__}')

Pandas Version is 2.2.2

In [5]:
file_path='/content/drive/MyDrive/EmergencyTriageDataset_Reduced_Dirty.csv'
df_raw=pd.read_csv(file_path)
df_raw.head(10)

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86  FEMALE  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0
5   6   42    Male  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0
6   7   75  Female  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0
7   8   25    Male  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0
8   9   67       0  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0
9  11   82  Female  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0

In [6]:
print(df_raw.dtypes) #viewing the data type

ID          int64
Age         int64
Gender     object
GCS        object
SBP        object
DBP       float64
MAP       float64
pulse      object
Temp       object
RR        float64
Fio2      float64
dtype: object

In [15]:
print(df_raw['Gender'].unique()) #viewing all the unique values in the gender column
print(f"\nTotal unique values: {df_raw['Gender'].nunique()}")

['Female' 'Male']

Total unique values: 2

In [16]:
print(df_raw['Gender'].value_counts())

Gender
Male      1176
Female    1029
Name: count, dtype: int64

In [17]:
df_raw['Gender']=(df_raw['Gender'].astype(str).str.strip().str.lower()) #stripping all strings to lowercase
print(df_raw['Gender'].value_counts())

Gender
male      1176
female    1029
Name: count, dtype: int64

In [22]:
gender_map={
    'female': '0',
    '0': '0',
    'male': '1',
    '1': '1'
}
df_raw['Gender_Clean'] = df_raw['Gender'].map(gender_map).fillna('Unknown') #mapping existing values in the column to 1/0 or Unknown if any values outside of what was defined is inputted
print(df_raw['Gender_Clean'].value_counts())

Gender_Clean
1    1176
0    1029
Name: count, dtype: int64

In [28]:
gender_one_hot=pd.get_dummies(df_raw['Gender_Clean'], prefix='Gender',dtype=int) #use one hot encoding to help with scalabilty and flexibility of the varying genders that may be inputted
df_raw=pd.concat([df_raw, gender_one_hot], axis=1)
print(gender_one_hot.head(10))

   Gender_0  Gender_1
0         1         0
1         0         1
2         1         0
3         1         0
4         1         0
5         0         1
6         1         0
7         0         1
8         1         0
9         1         0

In [34]:
df_raw = df_raw.drop(columns=['Gender', 'Gender_Clean'])

In [35]:
df_raw.head(10)

,ID,Age,GCS,SBP,DBP,MAP,pulse,Temp,RR,Fio2,Gender_0,Gender_1,Gender_0,Gender_1,Gender_0,Gender_1
0,1,34,15.0,93,67.0,75.67,128.0,36.8,14.0,21.0,1,0,1,0,1,0
1,2,20,15.0,130,90.0,103.33,80.0,37.0,16.0,21.0,0,1,0,1,0,1
2,3,77,14.0,163,105.0,124.33,92.0,36.8,18.0,21.0,1,0,1,0,1,0
3,4,23,8.0,100,60.0,73.33,100.0,37.0,12.0,100.0,1,0,1,0,1,0
4,5,86,15.0,150,90.0,110.00,85.0,37.0,19.0,21.0,1,0,1,0,1,0
5,6,42,15.0,100,60.0,73.33,99.0,37.0,20.0,21.0,0,1,0,1,0,1
6,7,75,15.0,120,80.0,93.33,99.0,37.0,25.0,21.0,1,0,1,0,1,0
7,8,25,15.0,100,50.0,66.67,85.0,37.0,25.0,21.0,0,1,0,1,0,1
8,9,67,15.0,110,70.0,83.33,78.0,37.0,16.0,21.0,1,0,1,0,1,0
9,11,82,15.0,153,82.0,105.67,130.0,37.0,19.0,21.0,1,0,1,0,1,0